services:
  - type: web
    name: automix-api
    env: python
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000

  - type: worker
    name: automix-worker
    env: python
    startCommand: python app/workers/worker.py